project:
  type: book
  output-dir: ..\ml-in-r-pub\

book:
  title: "Математичне моделювання в R"
  subtitle: "Матеріали підготовано для студентів 3-го курсу спеціальності економічна кібернетика"
  author: "Юрій Клебан"
  date: "10/02/2022"
  cover-image: img/cover.png
  site-url: https://kleban.github.io/ml-in-r-book/
  repo-url: https://github.com/kleban/ml-in-r-book/
  repo-branch: main
  sharing: [twitter, facebook, linkedin]
  favicon: img/favicon.png
  #google-analytics: "UA-XXXXXXXX"
  chapters:
    - index.qmd
    - 010-intro.qmd
    - part: 020-feature-engeneering.qmd
      chapters:
        - 023-feature-engeneering-woe-binning.ipynb
    - part: 030-supervised-learning.qmd
      chapters:        
        - 031-supervised-learning-linear-regression-1.ipynb
        - 032-supervised-learning-linear-regression-2.ipynb
        - 033-supervised-learning-desicion-trees-regression.ipynb
        - 034-supervised-learning-neutal-networks-regression.ipynb
        - 035-supervised-learning-logistic-regression.ipynb
        - 036-supervised-learning-desicion-trees-classification.ipynb
        - 037-supervised-learning-neural-network-classification.ipynb
    - part: 040-unsupervised-learning.qmd
      chapters:
        - 041-unsupervised-learning-clustering-kmeans-1.ipynb
        - 042-unsupervised-learning-clustering-kmeans-2.ipynb
        - 043-unsupervised-learning-clustering-kmeans-and-random-forest.ipynb
    #- references.qmd
 # appendices:
 #   - summary.qmd
  page-navigation: true
  page-footer: "Copyright 2022, Юрій Клебан" 
    
language: _language-ua.yml 

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: img/cover.png
    code-link: true
    css: css/style.css



