---
format:
  html:
    toc: true
    html-math-method: katex
---

# Про курс {.unnumbered}

Матеріали підготовлені для читання курсу ***"Вступ до прикладного математичного моделювання в R"*** `[08.435]` для студентів 3-го курсу, спеціальності економічна кібернетика.

## Опис навчальної дисципліни

Навчальна дисципліна спрямована на вивчення основ прикладного математичного моделювання з використаням різних видів моделей та підходів до їх побудови, а також удосокналенню процесів роботи з даними та моделями на основі мови R.

_Місце навчальної дисципліни у підготовці здобувачів_: програмні результати дисципліни використовуються під час вивчення таких навчальних дисциплін: “Математичні методи та моделі в аналізі великих даних”, “Економічна кібернетика”, “Дослідження операцій”, “Інтелектуальні технології моделювання у прийнятті рішень”. Закріплення на практиці здобутих програмних результатів відбувається під час проходження Навчальної практики з курсу «Економіко-математичне моделювання».

## Мета дисципліни

Мета навчальної дисципліни – формування у студентів теоретичних знань та практичних навичок використання мови програмування R для побудови,  навчання та оцінки якості математичних моделей на основі регресії, класифікації, кластеризації та асоціативних правил.

## Дотримання принципів доброчесності

Викладач та слухач цього курсу, як очікується, повинні дотримуватися Кодексу академічної доброчесності університету:

- [x] будь-яка робота, подана здобувачем протягом курсу, має бути його власною роботою здобувача; 
не вдаватися до кроків, що можуть нечесно покращити Ваші результати чи погіршити/покращити результати інших здобувачів;

- [x] якщо буде виявлено ознаки плагіату або іншої недобросовісної академічної поведінки, то студент буде позбавлений можливості отримати передбачені бали за завдання; 

- [x] не публікувати у відкритому доступі відповіді на запитання, що використовуються в рамках курсу для оцінювання знань здобувачів; 

- [x] під час фінальних видів контролю необхідно працювати самостійно; 
не дозволяється говорити або обговорювати, а також не можна копіювати документи, використовувати електронні засоби отримання інформації. 

Порушення академічної доброчесності під час виконання контрольних завдань призведе до втрати балів або вживання заходів, які передбачені Кодексу академічної доброчесності НаУОА. 

---

::: {.callout-note appearance="simple"}
Матеріали курсу створені з використанням ряду технологій: 

- [x] [`R` Language](https://www.r-project.org) - безкоштована мова програмування для виконання досліджень у сфері статистики, машинного навчання та візуалізацї результатів.

- [x] [`Quarto` Book](https://quarto.org) - система для публікації наукових та технічних текстів з відкритим кодом (`R`/`Python`/`Julia`/`Observable`).

- [x] [`JupyterLab`](https://github.com/jupyterlab/jupyterlab) - середовище розробки на основі [`Jupyter Notebook`](https://jupyter.org/). `JupyterLab` є розширеним веб-інтерфейсом для роботи з ноутбуками.

- [x] `Git`/`Github` - система контролю версій та, відповідно, сервіс для організації зберігання коду, а також публікації статичних сторінок.
:::


